### ISSUE TITLE
pod DSSparseArray fails

### ISSUE THREAD

**Issue by ExoticObjects** [LavaSlider/DSSparseArray#3]
`pod search DSSparseArray` 

results in:

`[!] Unable to find a pod with name matching DSSparseArray`

Similarly, 

`pod DSSparseArray`

results in:

`[!] Unable to find a specification for DSSparseArray`

So, although you have a podspec, it seems that your library is not actually available via cocoapods! Something went wrong somewhere along the way...

**Comment by LavaSlider** [comment]
Thanks I did not know; I do not use CocoaPods.
I will look into it. When perusing the CocoaPods website I did not find 
instructions that seemed to apply to this situation where the github 
repository already is in existence and just getting CocoaPods to work. 
Can you point me to some sort of tutorial or instructions?

Thanks.

**Comment by ExoticObjects** [comment]
This looks pretty good: 

http://davemeehan.com/technology/objective-c/cocoapods-creating-and-sharing-your-first-objective-c-open-source-project

**Comment by LavaSlider** [comment]
OK, I mostly followed the instructions from the link and I think it 
should be working now.
I did have a problem getting the podspec to validate as universal code 
(kept whining about unsigned long formatting in some NSLog() statements 
on iOS). I explicitly cast, so there should not be a problem, but I 
could not get past it. To get it functional I specified the platform to 
be OS X. The code is compatible with both iOS and OS X but the podspec 
says it is for OS X.

**Comment by ExoticObjects** [comment]
`pod search DSSparseArray` still fails:

`[!] Unable to find a pod with name matching DSSparseArray`

I doubt the problem is the NSLogs. But, in fairness, I think you should comment them out or use a compiler conditional or something, as it's frowned upon to ship a library that pollutes the developer's log with lots of statements. 

I'd change the podspec back to iOS, but again, I don't know if that's really the issue. Once `pod search DSSparseArray` succeeds, you'll be done! To test that you'll have to install cocoapods on your machine, which is simply `sudo gem install cocoapods`.

**Comment by LavaSlider** [comment]
I get no compiler warnings, the problem is only during the Podspec 
submission process when it runs some sort of lint process. The errors 
are definitely in the NSLogs. It gives the line numbers and says a %lu 
format is not compatible with an int argument but I have explicitly 
casted the argument to unsigned long. I have to do this because the 
value is an unsigned int in iOS and an unsigned long in OS X. They are 
given as warnings but block further podspec submission process. The 
change to OS X is only in the Podspec, nothing in the code.

When I go to cocoapods.org and type 'DSS' in the search box it finds 
three entries, one of which is DSSparseArray version 1.5.2.  I am not 
sure why 'pod search DSSparseArray' does not find it.

I will look into it a little more when I have a chance. I don't have 
access to my development computer right now.

**Comment by ExoticObjects** [comment]
What happens if you comment out the NSLogs, as developers using your code
don't want them anyway...?
